name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
        
      - name: Build
        env:
          NEXT_PUBLIC_BASE_PATH: '/web-fortuners'
          NEXT_PUBLIC_SITE_URL: 'https://thrivingmindfulways.github.io'
          NODE_ENV: 'production'
        run: |
          npm run build
          
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Create .nojekyll file
        run: |
          touch ./out/.nojekyll
          
      - name: Create 404 redirect
        run: |
          cp ./out/index.html ./out/404.html
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4